// <auto-generated />
using Formacion_Desarrollo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Formacion_Desarrollo.Migrations
{
    [DbContext(typeof(Formacion_DesarrolloContext))]
    [Migration("20180209125417_SecondRelease")]
    partial class SecondRelease
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Formacion_Desarrollo.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Name")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Formacion_Desarrollo.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("FechaFin");

                    b.Property<string>("Name")
                        .HasColumnName("Nombre");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("FechaInicio");

                    b.HasKey("Id");

                    b.ToTable("Proyecto");
                });

            modelBuilder.Entity("Formacion_Desarrollo.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<long>("DepartmentId");

                    b.Property<string>("LastName")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Name")
                        .HasColumnName("Nombre");

                    b.Property<string>("Phone")
                        .HasColumnName("Telefono");

                    b.Property<int>("PostalCode")
                        .HasColumnName("Cp");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Formacion_Desarrollo.Models.UserProject", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("ProjectId");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("UserProject");
                });

            modelBuilder.Entity("Formacion_Desarrollo.Models.UserProject", b =>
                {
                    b.HasOne("Formacion_Desarrollo.Models.Project", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Formacion_Desarrollo.Models.User", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
